import "./styles/globals.css";
import "animate.css";
import { Providers } from "./Providers";

export const metadata = {
  title: "Habya Registration App",
  description: "Generated by create NextJS app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <script
          src="https://checkout.razorpay.com/v1/checkout.js"
          async
        ></script>
      </head>
      <body className="flex flex-col min-h-screen bg-gradient-to-r from-gray-900 via-black to-gray-900 text-white overflow-x-hidden">
        <Providers>
          <main className="flex-grow">{children}</main>

          {/* Global Footer */}
          <footer className="w-full bg-black bg-opacity-30 text-gray-400 py-4 text-center text-sm px-4">
            © {new Date().getFullYear()} Habya. All rights reserved.{" "}
            <span className="mx-2">|</span>
            <a
              href="/footer/privacy-policy"
              className="hover:text-white underline transition duration-200"
            >
              Privacy Policy
            </a>
            <span className="mx-2">|</span>
            <a
              href="/footer/terms-and-conditions"
              className="hover:text-white underline transition duration-200"
            >
              Terms & Conditions
            </a>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
