import "./styles/globals.css";
import "animate.css";
import { Providers } from "./Providers";

export const metadata = {
  title: "Habya Registration App",
  description: "Generated by create NextJS app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
